[project]
name = "faststream-stomp"
description = "FastStream STOMP broker"
authors = [{ name = "Lev Vereshchagin", email = "mail@vrslev.com" }]
dependencies = ["faststream~=0.5", "stompman"]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }
keywords = ["faststream", "stomp", "artemis", "activemq", "messaging", "jms"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: System :: Networking",
    "Typing :: Typed",
]
dynamic = ["version"]

[project.urls]
repository = "https://github.com/vrslev/stompman"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["faststream[otel,prometheus]~=0.5"]

[tool.hatch.version]
source = "vcs"
raw-options.root = "../.."
fallback-version = "0"

[tool.hatch.build]
include = ["faststream_stomp"]
